In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/f1nalyze-datathon-ieeecsmuj/sample_submission.csv
/kaggle/input/f1nalyze-datathon-ieeecsmuj/validation.csv
/kaggle/input/f1nalyze-datathon-ieeecsmuj/train.csv
/kaggle/input/f1nalyze-datathon-ieeecsmuj/test.csv

Import the training dataset

In [2]:
import pandas as pd


# Replace 'filename.csv' with the actual CSV file name in the dataset

train= pd.read_csv(r'/kaggle/input/f1nalyze-datathon-ieeecsmuj/train.csv', low_memory=False)

# Display the first few rows of the DataFrame
train.head()

,resultId,racerId,driverId,constructorId,number,grid,position_x,positionText_x,positionOrder,points,...,points_y,position,positionText_y,wins,constructorRef,company,nationality_y,url,status,result_driver_standing
0,20025,833,642,51,2,1,1,1,1,9.0,...,3.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,922731975
1,20025,833,642,51,2,1,1,1,1,9.0,...,6.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,923172525
2,20025,833,642,51,2,1,1,1,1,9.0,...,6.33,4,4,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,923833350
3,20025,833,642,51,2,1,1,1,1,9.0,...,10.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,925195050
4,20025,833,642,51,2,1,1,1,1,9.0,...,10.33,4,4,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,926576775

Importing testing dataset

In [3]:

test = pd.read_csv(r'/kaggle/input/f1nalyze-datathon-ieeecsmuj/test.csv',low_memory=False)

# Display the first few rows of the DataFrame
test.head()

,resultId,racerId,driverId,constructorId,number,grid,position_x,positionText_x,positionOrder,points,...,driverStandingsId,raceId_y,points_y,wins,constructorRef,company,nationality_y,url,status,result_driver_standing
0,23949,997,4,1,14,13,8,8,8,4.0,...,12474,93,16.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,298739826
1,23949,997,4,1,14,13,8,8,8,4.0,...,12494,94,21.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,299218806
2,23949,997,4,1,14,13,8,8,8,4.0,...,12514,95,21.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,299697786
3,23949,997,4,1,14,13,8,8,8,4.0,...,12534,96,25.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,300176766
4,23949,997,4,1,14,13,8,8,8,4.0,...,12554,97,25.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,300655746

Importing the validation dataset

In [4]:

validation_ = pd.read_csv('/kaggle/input/f1nalyze-datathon-ieeecsmuj/test.csv', low_memory=False)

# Display the first few rows of the DataFrame
validation_.head()

,resultId,racerId,driverId,constructorId,number,grid,position_x,positionText_x,positionOrder,points,...,driverStandingsId,raceId_y,points_y,wins,constructorRef,company,nationality_y,url,status,result_driver_standing
0,23949,997,4,1,14,13,8,8,8,4.0,...,12474,93,16.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,298739826
1,23949,997,4,1,14,13,8,8,8,4.0,...,12494,94,21.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,299218806
2,23949,997,4,1,14,13,8,8,8,4.0,...,12514,95,21.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,299697786
3,23949,997,4,1,14,13,8,8,8,4.0,...,12534,96,25.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,300176766
4,23949,997,4,1,14,13,8,8,8,4.0,...,12554,97,25.0,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,+1 Lap,300655746

1. Define Missing Values:

2. Define a list of missing values to be treated as NaN (missing_value = ["\\N"]).
    Load Training and Testing Data:

    Load the training data CSV file (train.csv) into a DataFrame (df) using pandas.read_csv().
    Load the testing data CSV file (test.csv) into a DataFrame (test) using pandas.read_csv().
    Use na_values parameter to specify the custom missing value representation (\\N) to be treated as NaN.
    Use low_memory=False to ensure the file is read correctly, especially for large datasets.
    
3. Drop Rows with NaN Values:
    Remove rows with any NaN values in the training DataFrame (df_cleaned = df.dropna()).
    Remove rows with any NaN values in the testing DataFrame (test_df_cleaned = test.dropna()).
    
4. Display Cleaned Data:

Print the first few rows of the cleaned training DataFrame (df_cleaned.head()) to verify the data cleaning process.

In [5]:
missing_value = ["\\N"]

# Load the CSV file, specifying na_values and ensuring low_memory is set if needed
df = pd.read_csv(r'/kaggle/input/f1nalyze-datathon-ieeecsmuj/train.csv', na_values=missing_value, low_memory=False)
test = pd.read_csv(r'/kaggle/input/f1nalyze-datathon-ieeecsmuj/test.csv', na_values=missing_value, low_memory=False)
# Drop rows with NaN values
df_cleaned = df.dropna()
test_df_cleaned = test.dropna()
# Display the first few rows of the cleaned DataFrame to verify
print(df_cleaned.head())

Empty DataFrame
Columns: [resultId, racerId, driverId, constructorId, number, grid, position_x, positionText_x, positionOrder, points, laps, time_x, timetaken_in_millisec, fastestLap, rank, fastestLapTime, max_speed, statusId, year, round, circuitId, grand_prix, date, time_y, url_x, fp1_date, fp1_time, fp2_date, fp2_time, fp3_date, fp3_time, quali_date, quali_time, sprint_date, sprint_time, driverRef, driver_num, driver_code, forename, surname, dob, nationality, url_y, driverStandingsId, raceId_y, points_y, position, positionText_y, wins, constructorRef, company, nationality_y, url, status, result_driver_standing]
Index: []

[0 rows x 55 columns]

In [6]:
print(df.columns)

Index(['resultId', 'racerId', 'driverId', 'constructorId', 'number', 'grid',
       'position_x', 'positionText_x', 'positionOrder', 'points', 'laps',
       'time_x', 'timetaken_in_millisec', 'fastestLap', 'rank',
       'fastestLapTime', 'max_speed', 'statusId', 'year', 'round', 'circuitId',
       'grand_prix', 'date', 'time_y', 'url_x', 'fp1_date', 'fp1_time',
       'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date',
       'quali_time', 'sprint_date', 'sprint_time', 'driverRef', 'driver_num',
       'driver_code', 'forename', 'surname', 'dob', 'nationality', 'url_y',
       'driverStandingsId', 'raceId_y', 'points_y', 'position',
       'positionText_y', 'wins', 'constructorRef', 'company', 'nationality_y',
       'url', 'status', 'result_driver_standing'],
      dtype='object')

1. Define Features and Target Variable:

    Define a list of feature column names (features) to be used for the model.
    Define the target variable column name (target).
2. Check Columns in Training Data:

3. Print the column names of the training DataFrame (train) to verify the presence of the specified feature and target columns.
    Check Columns in Testing Data:

Print the column names of the testing DataFrame (test) to verify the presence of the specified feature columns.

In [7]:
# Example assuming corrected column name or creation if missing
features = [
    'driverId', 'constructorId', 'grid', 'points', 'laps', 'statusId',
    'year', 'round', 'circuitId', 'wins'
]
target = 'position_x'

# Check columns in train_df
print(train.columns)
# Check columns in test_df
print(test.columns)

# Update train_df and test_df with selected features and target
# train = train[features + [target, 'result_driver_standing']]
# test = test[features + [target, 'result_driver_standing']]

Index(['resultId', 'racerId', 'driverId', 'constructorId', 'number', 'grid',
       'position_x', 'positionText_x', 'positionOrder', 'points', 'laps',
       'time_x', 'timetaken_in_millisec', 'fastestLap', 'rank',
       'fastestLapTime', 'max_speed', 'statusId', 'year', 'round', 'circuitId',
       'grand_prix', 'date', 'time_y', 'url_x', 'fp1_date', 'fp1_time',
       'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date',
       'quali_time', 'sprint_date', 'sprint_time', 'driverRef', 'driver_num',
       'driver_code', 'forename', 'surname', 'dob', 'nationality', 'url_y',
       'driverStandingsId', 'raceId_y', 'points_y', 'position',
       'positionText_y', 'wins', 'constructorRef', 'company', 'nationality_y',
       'url', 'status', 'result_driver_standing'],
      dtype='object')
Index(['resultId', 'racerId', 'driverId', 'constructorId', 'number', 'grid',
       'position_x', 'positionText_x', 'positionOrder', 'points', 'laps',
       'time_x', 'timetaken_in_millisec', 'fastestLap', 'rank',
       'fastestLapTime', 'max_speed', 'statusId', 'year', 'round', 'circuitId',
       'grand_prix', 'date', 'time_y', 'url_x', 'fp1_date', 'fp1_time',
       'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date',
       'quali_time', 'sprint_date', 'sprint_time', 'driverRef', 'driver_num',
       'driver_code', 'forename', 'surname', 'dob', 'nationality', 'url_y',
       'driverStandingsId', 'raceId_y', 'points_y', 'wins', 'constructorRef',
       'company', 'nationality_y', 'url', 'status', 'result_driver_standing'],
      dtype='object')

1.  Convert Non-Numeric Values to NaN:

   Uses pd.to_numeric with errors='coerce' to convert non-numeric values in the specified features and target columns of both train and test            DataFrames to NaN.
   
2. Impute Missing Values:

    Creates a SimpleImputer instance with strategy='mean' to impute missing values (NaNs) with the mean value in both the train and test datasets.
    Copies train and test DataFrames to train_cleaned and test_cleaned, respectively.
    Imputes missing values in features columns for both train_cleaned and test_cleaned DataFrames using the imputer.
    
3. Impute Target Variable in Train Dataset:

    Uses another SimpleImputer instance with strategy='mean' to impute missing values in the target variable (position_x) of the train_cleaned           DataFrame.
    
4. Separate Features and Target Variable:

    Assigns the imputed features (X_train and X_test) and target (y_train) variables to separate variables for training (X_train_scaled, y_train) and     testing (X_test_scaled).
    
5. Feature Scaling:
    Uses StandardScaler to standardize the features (X_train_scaled and X_test_scaled) to have a mean of 0 and a variance of 1, which is a common         preprocessing step in many machine learning models.

In [15]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
# Convert non-numeric values to NaN
train[features + [target]] = train[features + [target]].apply(pd.to_numeric, errors='coerce')
test[features] = test[features].apply(pd.to_numeric, errors='coerce')

# Impute missing values in train and test datasets
imputer = SimpleImputer(strategy='mean')
train_cleaned = train.copy()
test_cleaned = test.copy()

# Impute features
train_cleaned[features] = imputer.fit_transform(train[features])
test_cleaned[features] = imputer.transform(test[features])

# Impute target variable (position_x) in train dataset
target_imputer = SimpleImputer(strategy='mean')
train_cleaned[target] = target_imputer.fit_transform(train[[target]])

# Separate features and target variable
X_train = train_cleaned[features]
y_train = train_cleaned[target].astype(float)
X_test = test_cleaned[features]

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

1. Random Forest Regressor Initialization:

    Initializes a Random Forest Regressor model (RandomForestRegressor) with n_estimators=10 and random_state=42. n_estimators determines the number     of trees in the forest.
    
2. Model Training:
    Trains the Random Forest Regressor model (rf_model) using the scaled training data (X_train_scaled, y_train).
    
3. Prediction:
    Uses the trained model (rf_model) to predict the target variable (Position) for the scaled test data (X_test_scaled).
    Submission DataFrame Creation:

4. Constructs a Pandas DataFrame (submission_df) containing the predictions (rf_predictions) and additional information (result_driver_standing) from    the test_cleaned dataset.

In [19]:

rf_model = RandomForestRegressor(n_estimators=10, random_state=42)  # Reduced number of estimators to 10
rf_model.fit(X_train_scaled, y_train)

# Predict using Random Forest on X_test
rf_predictions = rf_model.predict(X_test_scaled)

# Prepare submission DataFrame
submission_df = pd.DataFrame({
    'Position': rf_predictions,
    'result_driver_standing': test_cleaned['result_driver_standing']
})

Submitting in csv ..

In [20]:
print("Sample of submission DataFrame:")
print(submission_df.head())

# Save to CSV file
submission_df.to_csv('submission.csv', index=False)
print("Submission CSV file created successfully.")

Sample of submission DataFrame:
   Position  result_driver_standing
0       8.0               298739826
1       8.0               299218806
2       8.0               299697786
3       8.0               300176766
4       8.0               300655746
Submission CSV file created successfully.

So i have used random forest with 10 estimators only which reduced my accuracy u can do it nb gaussian and estimators upto 100 defining the depth and min sample nodes  which will lead to more accurate results

In [ ]:
+